
redis:
  host: "127.0.0.1"
  port: 6379
  password: "12345678"
  db: 0

# timeout for socket read/write
socketTimeout: 60
# epoll normal udp
connectionType: "keep_alive_tcp" # keep_alive_tcp: 不断开连接  regular_tcp: 超时断开
serverType: normal
logLevel: debug
platForm: "sync_server"
port: 8000


